### ISSUE TITLE
upscale v4 error: failed to validate prompt

### ISSUE THREAD

**Issue by Marcus-Arcadius** [fictions-ai/sharing-is-caring#8]
![image](https://github.com/fictions-ai/sharing-is-caring/assets/78793842/dc2fac9b-7e41-4a73-bb5f-6c385b90ef58)

**Comment by Marcus-Arcadius** [comment]
I got it to work with a refresh and page refresh :)

**Comment by vumichien** [comment]
I have the same problem @Marcus-Arcadius and it also shows this one. Do you know how to fix?
Prompt outputs failed validation
```
LoadImage:
- Custom validation failed for node: image - Invalid image file: ComfyUI_temp_kqydq_00005_b.png
```
